### ISSUE TITLE
Consider renaming do_test

### ISSUE THREAD

**Issue by klauer** [pcdshub/pmps_test#1]
https://github.com/pcdshub/pmps_test/blob/3a9c3b127476b78173e813e9b6f9751d062e575f/setup.py#L54

Maybe `pmps-do-test`? For tab completion on the command-line and disambiguation with other testing tools.

**Comment by klauer** [comment]
(Thoughts, @n-wbrown?)

**Comment by n-wbrown** [comment]
I agree, renaming is definitely a must. I was thinking of using `pmps_run_tests` as its consistent with our standard test running name. Maybe we start a standard of test/validation scripts being named as `[project_being_tested]_run_tests`.

**Comment by klauer** [comment]
Closed by #4
