### ISSUE TITLE
Test structure

### ISSUE THREAD

**Issue by klauer** [pcdshub/pmps_test#2]
### Background

* ADS symbol names are very similar to EPICS PV names 
    - Even better, they are structured in such a way that `FormattedComponent` prefixes should not be necessary
    - That is to say, `<most general>.<less general>.<least general>` is always how the symbols are named
* ophyd-ads is a prototype ophyd signal that builds on pyads, making it a bit easier to use (https://github.com/pcdshub/ophyd-ads)
   - pyads will hopefully be on conda-forge soon
   - Once that happens, we can get ophyd-ads up there as well

### Based on the above

We should consider making some ophyd Devices that represent PLC structures.
Then, we can run tests with that structure on the Python side.

### Miscellaneous ideas

* We can auto-generate ophyd devices based on tmc files, whether it's creating code or dynamically creating devices

**Comment by slacAWallace** [comment]
> We can auto-generate ophyd devices based on tmc files, whether it's creating code or dynamically creating devices

I like this, and funnily enough as I was working on the PMPS PVs for diagnostics today I was thinking along the same lines. I plan on building ophyd devices for pmps elements. And what do you know, there's a bit of a relationship between structs, FBs, and ophyd devices.

**Comment by klauer** [comment]
Turns out this is not our goal; closing. @n-wbrown want to summarize our discussion/new plan in a separate issue?
